return {
	symbolMap = {
		DEBUG = "", -- 
		ERROR = "", -- 
		INFO = "", -- 
		TRACE = "",
		WARN = "", -- 
		OTHER = "",
		HINT = "󰌶",
		LOCK = "󰌾",
		UNLOCK = "󰿆",
		BRANCH = "",
		INSTALLED = "󰄲",
		UNINSTALLED = "󰄱",
		PASTE = "󰆒",
		PENDING = "󰅢",
		MID_DOT = "•",
		RENAMED = "󰁕",
		DELETED = "", -- '✖'
		DELETED_2 = "",
		ADDED = "✚", -- '✚'
		ADDED_2 = "",
		MODIFIED = "",
		MODIFIED_2 = "",
		GIT_UNTRACKED = "",
		GIT_STAGED = "󰃨",
		GIT_IGNORED = "",
		GIT_UNSTAGED = "*",
		GIT_CONFLICT = "",
		BOOKMARK = "󰓹",
		BOOKMARK_ANNOTATION = "󰜢",
		ARROW_UP = "↑",
		ARROW_DOWN = "↓",
		ARROW_LEFT = "←",
		ARROW_RIGHT = "→",
		EXPANDED = "▾",
		COLLAPSED = "▸",
		EXPANDED_L = "",
		COLLAPSED_L = "",
		EXECUTABLE = "✦",
		FOLDER_CLOSED = "󰉋",
		FOLDER_OPEN = "󰝰",
		FOLDER_EMPTY = "",
		FILE = "󰈙",
	},

	kindSymbolMap = {
		Array = "󰅪", -- 
		Boolean = "󰨙", --  ◩
		Class = "󰠱", -- 
		Collapsed = "",
		Color = "󰏘",
		Constant = "󰏿", -- 
		Constructor = "🄲",
		Enum = "",
		EnumMember = "",
		Event = "", -- 
		Field = "", --  󰜢
		File = "󰈙",
		Folder = "󰉋",
		Function = "󰊕",
		Interface = "", -- 󰌗 
		Keyword = "󰌋", -- 
		Method = "󰊕",
		Module = "",
		Namespace = "󰦮", -- 
		Null = "∅",
		Number = "󰎠",
		Object = "󰅩",
		Operator = "",
		Package = "",
		Property = "",
		Reference = "󰈇",
		Snippet = "",
		String = "", -- 
		Struct = "", -- 󰆼
		Text = "󰉿",
		TypeParameter = "", -- '󰊄'
		Unit = "󰑭",
		Variable = "", -- 󰫧  𝕍 𝒗
	},

	modeMap = {
		["n"] = "N", -- 'NORMAL'
		["v"] = "V", -- 'VISUAL'
		["vs"] = "VISUAL",
		["V"] = "V-LINE",
		["Vs"] = "V-LINE",
		["\22"] = "V-BLOCK",
		["\22s"] = "V-BLOCK",
		["^V"] = "V-BLOCK",
		["multi"] = "Multi",
		["s"] = "SELECT",
		["S"] = "S-LINE",
		["\19"] = "S-BLOCK",
		["i"] = "I", -- 'INSERT',
		["ic"] = "INSERT",
		["ix"] = "INSERT",
		["R"] = "R", -- 'REPLACE'
		["Rc"] = "REPLACE",
		["Rx"] = "REPLACE",
		["Rv"] = "V-REPLACE",
		["Rvc"] = "V-REPLACE",
		["Rvx"] = "V-REPLACE",
		["c"] = "C",
		["cv"] = "EX",
		["ce"] = "EX",
		["r"] = "REPLACE",
		["rm"] = "MORE",
		["r?"] = "CONFIRM",
		["!"] = "SHELL",
		["t"] = "TERMINAL",
		["no"] = "O-PENDING",
		["nov"] = "O-PENDING",
		["noV"] = "O-PENDING",
		["no\22"] = "O-PENDING",
		["niI"] = "NORMAL",
		["niR"] = "NORMAL",
		["niV"] = "NORMAL",
		["nt"] = "NORMAL",
		["ntT"] = "NORMAL",
	},
}
