return {
	"stevearc/aerial.nvim",
	highlights = {
		AerialLine = { bg = "#3E1A00" },
		AerialFunction = { fg = "#589CFF" },
		AerialFunctionIcon = { fg = "#589CFF" },
		AerialObject = { fg = "#8DDA00" },
		AerialObjectIcon = { fg = "#8DDA00" },
		AerialArray = { fg = "#1C9A7B" },
		AerialArrayIcon = { fg = "#1C9A7B" },
		AerialVariable = { fg = "#B0B51D" },
		AerialVariableIcon = { fg = "#B0B51D" },
		AerialConstant = { fg = "#F46400" },
		AerialConstantIcon = { fg = "#F46400" },
	},
	opts = {
		backends = {
			["_"] = { "lsp", "treesitter", "markdown" },
			markdown = { "markdown" },
			man = { "man" },
		},
		highlight_on_hover = true,
		layout = { default_direction = "right", min_width = 20, max_width = 50 },
		show_guides = true,
		manage_folds = false,
		link_folds_to_tree = false,
		link_tree_to_folds = false,
		guides = {
			mid_item = "├─",
			last_item = "└─",
			nested_top = "│  ",
			whitespace = "  ",
		},
		filter_kind = {
			["_"] = {
				"Array",
				"Boolean",
				"Class",
				"Constant",
				"Constructor",
				"Enum",
				"EnumMember",
				"Event",
				"Field",
				"File",
				"Function",
				"Interface",
				"Key",
				"Method",
				"Module",
				"Namespace",
				"Null",
				"Number",
				"Object",
				"Operator",
				"Property",
				"String",
				"Struct",
				"TypeParameter",
				"Variable",
			},
		},
		ignore = {
			buftypes = false,
		},
	},
}
